[language-server.rust-analyzer.config]
cargo.buildScripts.enable = true
procMacro.enable = true
check.command = "clippy"
completion.callable.snippets = "add_parantheses"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
[[language]]
name = "rust"
auto-format = false
[[language]]
name = "nu"
file-types = ["nu"]
comment-token = '#'
language-servers = ["nu --lsp"]
# [[language]]
# name = "conf"
# file-types = ["conf"]
# comment-token = '#'
