# Author: RayGervais <raygervais@hotmail.ca>

# "ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.inlay-hint" = "base04"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base04", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base0D", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { fg = "base04", bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["reversed"] }
"string"  = "base0B"
"variable.other.member" = "base06"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0D"
"diff.delta" = "base08"
"diff.minus" = "base0C"

"diagnostic" = { modifiers = ["bold", "slow_blink"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base06"
"error" = "base0C"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
# background colour -> bg
# base00 = "#30504b" # Default Background
# complementary from wallpaper -> black
base01 = "#1a0c0c" # Lighter Background (Used for status bars, line number and folding marks)
# light_blue -> white
base02 = "#80b1bf" # Selection Background
# blue -> blue bold
base03 = "#c94a27" # Comments, Invisibles, Line Highlighting
# light_yellow -> white bold
base04 = "#fbf8f1" # Dark Foreground (Used for status bars)
# terminal foreground -> .
base05 = "#ff1300" # Default Foreground, Caret, Delimiters, Operators
# magenta -> magenta
base06 = "#de4035" # Light Foreground (Not often used)
# white = cyan -> 
base07 = "#000000" # Light Background (Never used)
# light_green -> green bold
base08 = "#fd693b" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# mauve = purple -> blue
base09 = "#c94a27" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
# yellow -> cyan
base0A = "#ec8737" # Classes, Markup Bold, Search Text Background
# cyan = light_cyan -> green
base0B = "#ff5c39" # Strings, Inherited Class, Markup Code, Diff Inserted
# green -> magenta bold
base0C = "#de4035" # Support, Regular Expressions, Escape Characters, Markup Quotes
# light_red -> yellow bold
base0D = "#fbeb96" # Functions, Methods, Attribute IDs, Headings
# light_gray -> red bold
base0E = "#f20f09" # Keywords, Storage, Selector, Markup Italic, Diff Changed
# old light_gray -> black bold
base0F = "#51100c" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
