# Author: RayGervais <raygervais@hotmail.ca>

# "ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.inlay-hint" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"variable.other.member" = "base06"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base08"
"diff.minus" = "base09"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base06"
"error" = "base09"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
# darkest from wallpaper (lighter???)
base00 = "#0e0e26" # Default Background
# complementary from wallpaper
base01 = "#12183c" # Lighter Background (Used for status bars, line number and folding marks)
# light_blue
base02 = "#2e5857"#"#92878d" # Selection Background
# blue
base03 = "#4f6e82" # Comments, Invisibles, Line Highlighting
# light_yellow
base04 = "#f9a53f" # Dark Foreground (Used for status bars)
# terminal foreground
base05 = "#fdffb1" # Default Foreground, Caret, Delimiters, Operators
# magenta
base06 = "#ffb3fe" # Light Foreground (Not often used)
# white = cyan
base07 = "#fbfdfc" # Light Background (Not often used)
# light_green
base08 = "#3dde76" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# mauve = purple
base09 = "#92878d" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
# yellow
base0A = "#f1a780" # Classes, Markup Bold, Search Text Background
# cyan = light_cyan
base0B = "#89fcff" # Strings, Inherited Class, Markup Code, Diff Inserted
# green
base0C = "#b5eace" # Support, Regular Expressions, Escape Characters, Markup Quotes
# light_red
base0D = "#eb544d" # Functions, Methods, Attribute IDs, Headings
# light_gray
base0E = "#8dd1e6" # Keywords, Storage, Selector, Markup Italic, Diff Changed
# old light_gray
base0F = "#49283b" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
