# Author: RayGervais <raygervais@hotmail.ca>

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.inlay-hint" = "base04"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base04", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base0D", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { fg = "base04", bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"variable.other.member" = "base06"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0D"
"diff.delta" = "base08"
"diff.minus" = "base0C"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base06"
"error" = "base0C"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
# background colour -> bg
base00 = "#30504b" # Default Background
# complementary from wallpaper -> black bold
base01 = "#5e8a74" # Lighter Background (Used for status bars, line number and folding marks)
# light_blue -> white
base02 = "#7f9b73" # Selection Background
# blue -> black bold
base03 = "#5e8a74" # Comments, Invisibles, Line Highlighting
# light_yellow -> black
base04 = "#061c17" # Dark Foreground (Used for status bars)
# terminal foreground -> .
base05 = "#f7f6cb" # Default Foreground, Caret, Delimiters, Operators
# magenta -> blue
base06 = "#06aee0" # Light Foreground (Not often used)
# white = cyan -> white
base07 = "#7f9b73" # Light Background (Never used)
# light_green -> yellow bold
base08 = "#fcce5e" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# mauve = purple -> cyan
base09 = "#4ecac6" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
# yellow -> white bold
base0A = "#a39d5d" # Classes, Markup Bold, Search Text Background
# cyan = light_cyan -> magenta bold
base0B = "#f96d98" # Strings, Inherited Class, Markup Code, Diff Inserted
# green -> red
base0C = "#f46221" # Support, Regular Expressions, Escape Characters, Markup Quotes
# light_red -> green bold
base0D = "#91db6d" # Functions, Methods, Attribute IDs, Headings
# light_gray -> cyan bold
base0E = "#a4e0e4" # Keywords, Storage, Selector, Markup Italic, Diff Changed
# old light_gray -> black
base0F = "#061c17" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
