#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")"; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# wallpaper
feh --bg-fill "${SCRIPTPATH}/tetris.png" -B white

# picom
pkill picom
sleep 0.2
picom --config "${SCRIPTPATH}/picom.conf" &

# wezterm
if [ -f ~/.config/wezterm/theme.lua ]; then
    rm ~/.config/wezterm/theme.lua
fi
ln -s "${SCRIPTPATH}/theme.lua" ~/.config/wezterm/theme.lua

# helix
if [ -f ~/.config/helix/themes/leftwm.toml ]; then
    rm ~/.config/helix/themes/leftwm.toml
fi
ln -s "${SCRIPTPATH}/helix/theme.toml" ~/.config/helix/themes/leftwm.toml

# gitui
if [ ! -f ~/.config/gitui/zelda.ron ]; then
    ln -s "${SCRIPTPATH}/gitui.ron" ~/.config/gitui/zelda.ron
fi

# nushell startup
if [ -f ~/.config/nushell/startup.nu ]; then
    rm ~/.config/nushell/startup.nu
fi
ln -s "${SCRIPTPATH}/startup.nu" ~/.config/nushell/startup.nu

# darkman
darkman set dark

# cava
$SCRIPTPATH/cava/cava.nu

# lemonbar
pueue kill -g bar; pueue start -g bar; (cd ${SCRIPTPATH}/lemonbar; nu "./lemonbar.nu")
